
spring:

  .main:
    banner-mode: off

  .jpa:
#    generate-ddl: true
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect

  .profiles.active: local

task.template.allowMultipleTasks: false
