
spring:
  .h2.console:
    enabled: true
    path: '/console'

  .datasource:
    url: 'jdbc:h2:C:/Users/Public/todoDb'
    username: 'sa'

management:
  endpoints:
    web:
      exposure:
        include: '*'